# Generated by Django 2.2.3 on 2019-09-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='slime',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
